# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  # - pre-push
  # - pre-merge-commit
default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.4
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies: # NOTE: include all project deps + typing stubs
          - "numpy"
        # exclude: (_deprecated|src/_deprecated)/.*\.py
        # exclude: |
        #     (?x)^(
        #         path/to/file1.py|
        #         path/to/file2.py|
        #         path/to/file3.py
        #     )$
        # entry: mypy .
        # pass_filenames: false
