# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
  # - pre-push
  # - pre-merge-commit
default_language_version:
  python: python3.13
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.26
    hooks:
      - id: uv-lock
      - id: uv-sync
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.13
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        description: "Run `ty check` for Python type checking"
        entry: uv run ty check --force-exclude
        language: python
        types_or: [python, pyi, jupyter]
        require_serial: true
        additional_dependencies: []
        pass_filenames: false
