version: "1.0"

services:
  develop:
    image: python-project
    container_name: python-project-develop
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host
    # environment:
    #   SSH_AUTH_SOCK: /run/host-services/ssh-auth.sock
    #   DISPLAY: $DISPLAY
    volumes:
      - type: bind
        source: ./
        target: /app
      # - type: bind
      #   source: $SSH_AUTH_SOCK
      #   target: /run/host-services/ssh-auth.sock
      # - type: bind
      #   source: /tmp/.X11-unix
      #   target: /tmp/.X11-unix
      # - type: bind
      #   source: ~/.Xauthority
      #   target: /root/.Xauthority
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        python -m pip install -e .[dev]
        /bin/bash
    # command:
    #   - |
    #     git config --global --add safe.directory /app
    #     python -m pip install -e .[dev]
    #     /bin/bash

# docker run --rm -it --gpus=all --network=host --env DISPLAY=$DISPLAY --mount type=bind,source=$HOME/.Xauthority,target=/root/.Xauthority --env SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock --mount type=bind,source=$SSH_AUTH_SOCK,target=/run/host-services/ssh-auth.sock -v $PWD:/app Python-project sh -c "git config --global --add safe.directory /app && zsh"