[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
authors = [{ name = "Paul Rademacher", email = "paul.rademacher@nrl.navy.mil" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = ["numpy"]
description = "A template for Python project layout and configuration"
name = "Python-project"
readme = "README.md"
requires-python = ">=3.11"
version = "0.0.1"

[project.optional-dependencies]
extras = [
  "tensorboard",
  "torch-tb-profiler",
  "PyQt6",
  "tqdm",
  "types-tqdm",
  "PyYAML",
  "types-PyYAML",
  "ipywidgets",
  "ipykernel",
]
dev = [
  "black",
  "ruff",
  "mypy",
  "hatch",
  "pytest",
  "pytest-cov",
  "Sphinx",
  "furo",
  "ipython",
]

[project.urls]
"Bug Tracker" = "https://github.com/rademacher-p/Python-project/issues"
"Homepage" = "https://github.com/rademacher-p/Python-project"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
ignore-vcs = true
packages = ["src/python_project"]
# only-include = ["src/python_project"]
# sources = ["src"]

[tool.hatch.envs.default]
python = "3.11"
features = ["dev"]
post-install-commands = ["pip install --upgrade pip", "mypy src/", "mypy --install-types"]

# [tool.hatch.envs.default.env-vars]
# PIP_EXTRA_INDEX_URL = "https://download.pytorch.org/whl/cu118"

[tool.ruff]
src = ["src"]
select = [
  "F",   # pyflakes
  "E",   # pycodestyle
  "W",   # pycodestyle
  "C90", # mccabe
  "I",   # isort
  "N",   # pep8-naming
  "D",   # pydocstyle
  "B",   # bugbear
  "UP",  # pyupgrade
]
ignore = [
  "D1",   # missing docstrings
  "B905", # zip w/o explicit `strict=`
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"

[[tool.mypy.overrides]]
module = ["python_project.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = ["--cov=src/python_project"]
filterwarnings = ["ignore::DeprecationWarning"]
testpaths = ["tests/"]

[tool.coverage.run]
data_file = "tests/.coverage"
